name: Auto-Green

on:
  schedule:
    - cron: "0 0 * * 0-5"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Commit
        run: |
          git config --local user.name "iflycn"
          git config --local user.email "iflycn@gmail.com"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push