name: Auto-Green

on:
  workflow_dispatch:
    inputs:
      log:
        description: "Commit Log"
        required: false
        default: "a commit a day keeps your girlfriend away"
  schedule:
    - cron: "0 0 * * 0-5"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Commit
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@gmail.com"
          git remote set-url origin https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "${{ github.event.inputs.log }}"
          git push